### GET auth/: 16:46, Show the ADMIN PAGE 
GET  http://localhost:8080/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiZW1haWwwM0BnbWFpbC5jb20iLCJpYXQiOjE2NTMyMDkzNTksImV4cCI6MTY1MzIxMDI1OX0.nEzfvumlCp81uzm8WF0PCMn_shh2cS7oAMSfPcNn0H4


### POST auth/login: 15:54, using new password 
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "email03@gmail.com",
  "password": "Password1!"
}

### POST auth/password-new: 15:48 
POST http://localhost:8080/auth/password-new
Content-Type: application/json

{
  "password_reset_token": "$2b$10$RqPMN7hWzk.M3knITzpI9.ayrW/VBdHrI8RzVk1xMIWEGj6EW7LCu",
  "new_password": "Password1!"
}



### POST local/login: 15:44 
POST http://localhost:8080/auth/password-reset
Content-Type: application/json

{
  "email": "email03@gmail.com"
}



### POST local/login: 13:53 
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "email03@gmail.com",
  "password": "P@ssword!"
}

### POST local/register: 
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "admin1@gmail.com",
  "password": "P@ssword!1",
  "role": "ADMIN"
}


### POST local/register: 
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "email05@gmail.com",
  "password": "P@ssword!",
  "role": "USER"
}



### Pexel API Call:
GET https://api.pexels.com/v1/search?query=people
Authorization: 563492ad6f9170000100000143b1404b9f7e475d8c8831687a2e36a9
